// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0dwGaIfxaRO-WZ5Vpjb396xlDjA_HuW4',
    appId: '1:560402678372:web:4b4c7662e2e8ad76a79571',
    messagingSenderId: '560402678372',
    projectId: 'pracfire-c0994',
    authDomain: 'pracfire-c0994.firebaseapp.com',
    storageBucket: 'pracfire-c0994.appspot.com',
    measurementId: 'G-EW25FH935K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaGCYfhXM0ovLociINU1kUeVlHUKE9Zs0',
    appId: '1:560402678372:android:0d8d56a68a260d32a79571',
    messagingSenderId: '560402678372',
    projectId: 'pracfire-c0994',
    storageBucket: 'pracfire-c0994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGxW9nF-VS73NpO1lgc2XtGgRoH_BaLns',
    appId: '1:560402678372:ios:c6dba23fe1983adca79571',
    messagingSenderId: '560402678372',
    projectId: 'pracfire-c0994',
    storageBucket: 'pracfire-c0994.appspot.com',
    iosBundleId: 'com.example.practfire',
  );
}
